spring:
  datasource:
    url: jdbc:postgresql://localhost:5433/testdb
    username: testuser
    password: testpass
    driver-class-name: org.postgresql.Driver

AES_SECRET_KEY: VICV&EZWVr"G8e2s+Xmg}bOy^&VK6gV+

frontend:
  url: http://localhost:3000
