spring:
  config:
    activate:
      on-profile: seed
  main:
    web-application-type: none

AES_SECRET_KEY: VICV&EZWVr"G8e2s+Xmg}bOy^&VK6gV+

stripe:
  key:
    secret: sk_test_fake_key

seed:
  random-seed: 42
  client-count: 10
